#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    default_indent = 4


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[options]
    autocomplete_method = "coc"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true
  [layer.clang_std]
    cpp = "c17"

[[layers]]
  name = "format"

[[layers]]
  name = "lsp"
  filetypes = [
    "c",
    "cpp"
  ]
  [layers.override_cmd]
    c = ["clangd"]
    cpp = ["clangd"]

[[layers]]
  name = "gtags"

[[layers]]
  name = "fzf"

[[custom_plugins]]
  repo = "liuchengxu/vista.vim"
  merged = false

[[custom_plugins]]
  repo = "neoclide/coc.nvim"
  merged = false

[[custom_plugins]]
  repo = "preservim/tagbar"
  merged = false

[[custom_plugins]]
  repo = "vhdirk/vim-cmake"
  merged = false

[[custom_plugins]]
  repo = "rhysd/vim-clang-format"
  merged = false

[[custom_plugins]]
  repo = "vim-scripts/DoxygenToolkit.vim"
  merged = false
